### ISSUE TITLE
Unable to open backpack and UI suggestion

### ISSUE THREAD

**Issue by ual1n** [BeansGalaxy/Beans-Backpacks-2#100]
I'm not able to open the backpack even though I have a bind for the mod, I need to take it off my back, place it on the ground and use the right mouse because the bind doesn't work, in addition, the backpack identity needs to be adjusted, such as "Leather Backpack ", "Gold Backpack" and "Netherite Backpack", instead of "entity:beansbackpack.backpack" (I can see using The One Probe mod).

As a suggestion, I would like the backpack slots to be visible and the mod to have compatibility with the Mouse Tweaks mod, so that I can organize the items more easily, because currently the slots are invisible and the organize buttons do not appear, so, At least having the option to adjust the opacity of the slots would be useful.

Game version: 1.20.2 (Fabric)
Mod version: v0.16-v2

**Comment by BeansGalaxy** [comment]
Just to clear up any confusion, you can only access the last item inserted while the backpack is equipped. The hotkey is like a second shift click but instead of moving items to/from your hotbar and inventory it moves items to/from the backpack inventory. Are you saying you can't insert/take items by clicking on the backpack item?

I'll just updated how the names are stored in the code so it must've broke, I'll check that out.

And Mouse Tweaks is a fantastic mod I'll try to fix that.

**Comment by ual1n** [comment]
Oh I see, thank you very much for the response and I apologize for the delay. I thought the shortcut key was to open the backpack inventory, but according to the explanation it is only used to move items.

**Comment by BeansGalaxy** [comment]
Yeah, the Inventorio mod takes over shift click to move items to and from your extra inventory but I found it annoying when moving items to your hotbar so ctrl click is for the backpack inventory and shift click is for the hotbar. Also you can use the hotkey and right click on a block to place the backpack down quickly. 

In the next version 1.20-0.21-v2, I added a help menu to clear this stuff up because backpack mods have been around since minecraft has had more items than inventory slots. It seems everyone has a sort of expectation of backpack mods and when they try mine it's super confusing.

**Comment by BeansGalaxy** [comment]
Hey! Just went through everything you said and was doing some testing just to realize you're in MC 1.20.2. 1.20.2 isn't supported anymore since my mod is still in beta & development is just so much faster if I focus only on 1.20.1 since it's the most popular version.

The 1.20.1 mod is complete in terms of features, I'm cleaning up a lot of code and making sure I get the last of the critical bugs out before fully releasing it. Then I'll be going back to 1.20.2, likely within a month.

While I was developing 20.2 & 20.1 I had no issues switching between versions but now that 20.2 is so outdated I'd suggest making a backup of your world before downgrading and just flying around to see if everything still works.

Nonetheless, thanks for your support!
