### ISSUE TITLE
Keep Back Slot gamerule

### ISSUE THREAD

**Issue by Ev3rgarden** [BeansGalaxy/Beans-Backpacks-2#101]
Hi there!

Firstly, thank you for creating this amazing and adorable mod! I understand that my feature request may have a very low priority, but if it were possible to have an option that could be turned on, perhaps in the config, where the backpack and its contents do not drop when this option is enabled, it would be greatly appreciated. Maybe in a future update? :3

**Comment by BeansGalaxy** [comment]
Sure! Just to be clear, when a player dies you want to keep back slot's item on the player but on death still drop the player's inventory?

**Comment by Ev3rgarden** [comment]
I was thinking that when the player dies, they usually lose their items except for the backpack and the items within it, acting like a mini safe inventory to make death less harsh!

**Comment by BeansGalaxy** [comment]
I've got you, so when a player respawns their inventory's empty except for the backpack they were wearing. This should be easy since in much earlier versions this was actually an issue I was having lol. 

I'll try to get it out in 20.1-0.22-v2. Sorry it didn't make this update, buttons are surprisingly really complicated

**Comment by BeansGalaxy** [comment]
Added in 20.1-0.23-v2! You can enable it by using the command `/beansmod gamerule keepBackSlot true`
