### ISSUE TITLE
Removing the backslot with elytra

### ISSUE THREAD

**Issue by gluzzie** [BeansGalaxy/Beans-Backpacks-2#103]
i'm looking on your wiki and I know it's like I have to make a data pack and stuff but I am really confused.

I'm trying to get rid of the elytra being able to go into the curios mod back slot and the ability that the create copper and netherite back tank don't take up a slot with the backpack 

I'm just winding if I can get a little help (I don't understand github) 

thank u for reading this message :P

**Comment by BeansGalaxy** [comment]
With curios installed you cannot disable the elytra. That's because how curios wants me to label the item before the game is loaded so I can't change it later depending on data.

As for the Back Tanks, start by using my data pack template.

[download Modify Data Template.zip](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14750045/Modify.Data.Template.zip)

Assuming you've used resource packs or data packs before... 

1. Open up `disables_back_slot` on your computer using note pad. The file should have the path `data/beansbackpacks/modify/disables_back_slot'
2. Inside write `!create:copper_backtank, !create:netherite_backtank`. The `!` means "ignore this item"\
3. Put your new data pack inside of your world's `datapacks` folder

The back tanks should not disable the back slot anymore. Let me know if you have any more questions, I really didn't understand data packs or github at all until I started modding so I understand getting completely lost when trying to start ;D

**Comment by gluzzie** [comment]
OMG IT WORKED THANK U SO MUCH UR AMAZING
i just gotta figure out a way to get rid of the elytra :/
but thank u soso much these actually helps me so much

**Comment by BeansGalaxy** [comment]
!!! Awesome! inside of `elytra_items` if you write `!minecraft:elytra` it disables the elytra entirely in my mod but with curios you might still be able to equip it and it might be a little buggy idk exactly. You can definitely try it anyways.

**Comment by gluzzie** [comment]
omg it worked thank u
