### ISSUE TITLE
On a server, when you die, the backpacks drop and delete all the items inside them.

### ISSUE THREAD

**Issue by MarbleHoarder** [BeansGalaxy/Beans-Backpacks-2#108]
Version: 20.1 - 0.21-v2
Loader: Fabric 0.15.7

This behaviour does not accrue while playing on the same mod list in singleplayer.

**Comment by BeansGalaxy** [comment]
can you post your latest log of the server or upload the modlist?

**Comment by MarbleHoarder** [comment]
[Modlist.json](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14813053/Modlist.json)
I don't have the logs on me right now but i'll get them as soon i can.

**Comment by BeansGalaxy** [comment]
if you run the server, die, stop the server and upload that log. That would help too. I can't really diagnose the issue with all the mods installed.

Also if you have any mods that effect player respawning like a grave mod. That could be causing the issue since this is a reoccurring issue with those types of mods.

**Comment by MarbleHoarder** [comment]
[latest.log](https://github.com/BeansGalaxy/Beans-Backpacks-2/files/14815134/latest.log)
here is the log, there is not grave mod installed but I'll try to find if its a mod compatibility issue.

**Comment by BeansGalaxy** [comment]
Found the error! When I first set up trinkets I put some essential stuff in a client only part of the mod when it should have been put somewhere the client and server can both access it. This must've been an issue for a while and, since I've been cleaning up a lot of code, I must've removed a bug cancelling out this one.

Thanks for all your help! Keep an eye out for 20.1-0.22-v2 ;)
