### ISSUE TITLE
suggestion - add a way to configure/remove inventory backpack guide button

### ISSUE THREAD

**Issue by Liamgrayskull** [BeansGalaxy/Beans-Backpacks-2#113]
Some way of enabling/disabling the inventory button would greatly help in modpack development, or maybe only showing up when a backpack valid item is equipped

**Comment by BeansGalaxy** [comment]
I originally wanted a button to disable the menu until a new tab was unlocked but since I don't have config setup for the mod, I don't have any way to save the settings to the client. 

I do plan on adding support for cloth config and mod menu soon and when I do I'll make sure to add a setting to disable the menu completely.

**Comment by BeansGalaxy** [comment]
Added Config in the latest update! Just look through my mod's config file and search for something like Menu Visibility. Setting it to DISABLE will always hide the menu. *([Read More](https://github.com/BeansGalaxy/Beans-Backpacks-2/wiki/Configurations#modify-client-sided-features))*
