### ISSUE TITLE
Trim Textures

### ISSUE THREAD

**Issue by stooert** [BeansGalaxy/Beans-Backpacks-2#114]
How to add trim textures for modded materials?

Eg for pigsteel mod

**Comment by BeansGalaxy** [comment]
https://github.com/BeansGalaxy/Beans-Backpacks-2/wiki/Configurations#adding-modded-trims

This is the wiki page for adding modded trims. I recently re-wrote it so if you have any more questions don't be afraid to ask since I want my wiki as clear as possible.

Also if this only adds support for trim templates not materials. Materials should automatically work and if not then this is an issue.

**Comment by BeansGalaxy** [comment]
Yeah this is really a half documentation error and half misunderstanding error. All you need to do is declare the location of the color palette. Since I never did that the mod doesn't know where to the colors for pigsteel trims are and have no location.

I included it's textures in the next update and I'll update the wiki page too.

**Comment by stooert** [comment]
Cool, thanks.
