### ISSUE TITLE
Elytra + Create Compat

### ISSUE THREAD

**Issue by egegokdenizduman** [BeansGalaxy/Beans-Backpacks-2#116]
Elytra on backpack slot does not work on Fabric 1.20.1. Flying animation starts for a split second and returns to freefalling again. Also equipping Create's backtank makes the backpack slot disappear. I think that the second issue may be unfixable due to being caused by Create. I suspect the issue is casued by the backtank not being counted as an armor piece (can't shift click to smithing table unlike elytra). Or it could be due to a common fabric library tag both you and Create using to make the item appear in players' backs. The line of code that checks if there is a backpack or not could be cheking using that common tag and making the slot appear as equipped. I think latter might be the case.

**Comment by BeansGalaxy** [comment]
So the Back Slot disappearing when a Back Tank is equipped is actually a feature since I didn't want the models of it and the backpack clipping into each other. I'm working on adding config right now and I could include a setting to not render the backpack if a conflicting Chestplate is equipped.

As for the Elytra not deploying correctly I'll look into that. It's likely an issue with the server not equipping it correctly. The client knows you have it equipped and you start flying then the server says you don't then updates the client a frame or so later.

**Comment by BeansGalaxy** [comment]
Hey I was able to re-create the bug you were having with the elytra not deploying. If I equip it in creative mode then I'm unable to deploy it. It's because the server never equips it but the client does, you can tell by switching into survival the backpack becomes a ghost item if you try to remove it.

I'll make sure to sync the slot over to the server in a coming update but *in my testing* it works just fine if you equip it in survival.

**Comment by BeansGalaxy** [comment]
The creative Back Slot is syncing properly in 20.1-0.24-v2! Thanks for your help :)
