### ISSUE TITLE
Add an option to disable to quickly placing the backpack on the ground

### ISSUE THREAD

**Issue by Jnss98b** [BeansGalaxy/Beans-Backpacks-2#119]
Right now it's possible to place down the backpack while equipped by holding shift and right clicking the ground. This has been quite annoying to me and an option to disable this behavior would be very appreciated

**Comment by BeansGalaxy** [comment]
Yeah, you can change the key bind for it. If it's unbound it'll take the key you use for sprint, or if its bound to a mouse key it'll instantly place it without a right click. There's no way to really unbind it since you need to take if off to access **all** the items but you could bind it to a key like `]` or `PgUp` and never press it.
