### ISSUE TITLE
"Equipment Disabling the Back Slot is dumb" -author

### ISSUE THREAD

**Issue by garretttm1007** [BeansGalaxy/Beans-Backpacks-2#135]
![image_2024-05-01_080415859](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/148989045/26c35604-002b-41da-82bb-c38c63d31a91)

Whenever a backtank is equipped, the backpacks become permanently unequipable.

**Comment by Sylphily** [comment]
more information would probably be needed, like logs, and i would crack a guess that its the same bug as #134

**Comment by BeansGalaxy** [comment]
So the create back tanks actually disable the back slot because their models would overlap and I imagine the back tank being worn on the back. It should say "Copper Backtank is already equipped" but instead it says [Air] so that's a bug. 

Possibly might stop backpacks from being rendered if an item like that is equipped instead of disabling the slot entirely and I would remove Winged Backpacks to just allow elytra to be worn with backpacks too. This feature is very un-vanilla and is like a bright light for bugs soo.... consider this gone in a update soon.

**Comment by BeansGalaxy** [comment]
@Sylphily Possibly in the 1.20.5 version. Basically half of my code can be thrown away because the new item components can handle a lot of the heavy lifting my mod does. 

Originally I planned for Back Tanks, Elytra & other modded items to be exclusively worn in the back slot but this isn't the right way to do it. It ended up being much more complicated than I first thought so instead it's this half baked idea that's only been causing problems, I'll shelf it and try again completely with 1.20.5.

**Comment by BeansGalaxy** [comment]
Removed in 0.27-v2, I'll look at adding this feature back with 1.20.5's components but it that's not good enough, just think of how well I'll be sleeping by not waking up in fear of a new bug report pointing back to this feature 😴 💤 🛌 ⏰ 💯
