### ISSUE TITLE
GUI display bug

### ISSUE THREAD

**Issue by VitaminJake** [BeansGalaxy/Beans-Backpacks-2#136]
When stacking past 64 of any item in either the backpack UI or the internal inventory little spot, it blanks the entire display. The items can still be retrieved, just not seen. Tested with multiple backpacks (leather, wing, end), tested with vanilla and modded items. At least it's in a _playable_ state, no critical game break with this.

(sorry bean man, cut off one head and three more grow out)

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/162518177/86557529-fd3d-4860-90bb-da27b3718295

**Comment by BeansGalaxy** [comment]
this mod's about to be single player only soon lmao. I can't re-create this, do you mouse tweaks installed and is this in single player?

**Comment by VitaminJake** [comment]
Not a mouse tweaks interaction, tried with it uninstalled. Can confirm 100% only occurs on server. Singleplayer working fine.

**Comment by BeansGalaxy** [comment]
I'll do some more server testing then. I've really been pushing to get out of beta so a lot of code had to be re-written, that's why every update there seems to be a lot of new bugs without any changes. Thanks for hanging on and the support, but yeah, unless there's any worse bugs than a little server-client desync then wait until the full release :)) If these bugs are like a hydra then I must be Steve Rodgers 💯💯 💯

**Comment by BeansGalaxy** [comment]
Solved in 0.27-v2. Minecraft's default networking only allows to send item stacks with the size -128 -> 127 since there shouldn't ever be an item stack in the game above 64. Adding 200 torches causes the number to overflow and it would send the client -72 and since it's empty the menu would remove it. It wouldn't happen in single player since it's never sent through the internet and can still handle items being as large as they want.
