### ISSUE TITLE
[suggestion] backpack locate command

### ISSUE THREAD

**Issue by letruxux** [BeansGalaxy/Beans-Backpacks-2#167]
because of the easy shortcut i sometimes acidentally place my backpack and lose it, it would be great to locate it

**Comment by JuceInUse** [comment]
Do `/execute as @e[type=beansbackpacks:backpack] run tp @s ~ ~ ~` to teleport to the nearest backpack. Just make sure it's still within render distance

**Comment by BeansGalaxy** [comment]
the execute command is the best answer for this. If you have F3 open while in your Ender Backpack it shows all of it's locations since it's linked to a player so it's easy to store and access but regular backpacks aren't as reliable in remembering who placed them and don't have a central place to search which ones are yours so to locate them in unloaded chunks won't be something I can add.

You can also rebind the place backpack key off of sprint if you accidentally keep placing it through the keybind screen. If it's REALLY bad I suggest binding it to `]` and you'll never accidentally place it again :P

Sidenote: I've been looking into the lodestone block's code to see if I can pair a compass with netherite backpacks. It looks promising but that's in 1.21 code and A LOT has changes since 1.20.1 so I couldn't say now how plausible that function would come to 1.20.1

**Comment by letruxux** [comment]
a lodestone-like behavior would be great, version doesn't matter, i have to upgrade minecraft anyways so it's not a big deal.
