### ISSUE TITLE
Breaking all recipes display | Suggestion: Config?

### ISSUE THREAD

**Issue by HaipaDev** [BeansGalaxy/Beans-Backpacks-2#22]
Hi, honestly very cool approach to backpacks, too bad there is no config for example allowing to switch elytra backslot, or allowing it on chest etc etc

My biggest issue is it breaks all recipes, not sure why exactly, skimmed through the logs quickly and didnt notice anything in particular
I have a quite large modpack but Beans Backpacks has been identified as the sole culprit of breaking all recipes not showing in either the vanilla recipe book nor REI (REI showed only the useless tag tab)
~~(also shift clicking for ex. a shield crashes in creative with a mod called [Inventory Control Tweaks](https://modrinth.com/mod/inventory-control-tweaks),~~ because the back slot is completely disabled in creative (or maybe doesnt show because of mods like Trinkets)~~

**Comment by BeansGalaxy** [comment]
I'll have to add a config option specifically for elytra since many mods add their own elytra-like items, but to return it to the original vanilla functionality, [read this.](https://github.com/BeansGalaxy/Beans-Backpacks-2/blob/master/assets/examples/Create%20Your%20Own.md) I use data packs for the config in my mod, by having the elytra disable the back slot it'll revert my mod's changes. 

I know the recipes have been broken up until I re-wrote their code in 0.7-v2. Make sure you're using that version of the mod. If it's still broken post your modpack and I'll see if my mod is having any compatibility issues with any other mods.

**Comment by BeansGalaxy** [comment]
I tried looking into how I'd support other mod's elytra and now that I have support for curios/trinkets I think I'd suggest using another mod like Elytra Slot. I'll leave support in for if you don't have either installed but if you're going to use curios/trinkets anyways then Elytra Slot is the better choice. In versions 20.1-0.6 & 20.2-0.11 I'll be removing it.
> I only added the elytra because I couldn't figure out how to use APIs and now I cant figure out compatibility so eff it, get your elytra slot from the elytra guy im just the backpack guy ¯\\\_(ツ)_/¯
