### ISSUE TITLE
Right clicking the empty slot of the backpack causes a crash

### ISSUE THREAD

**Issue by Emery319** [BeansGalaxy/Beans-Backpacks-2#39]
Minecraft 1.20.1
Forge 47.2.0
BeansPacks 0.7-v2

Right clicking on an empty slot of the backpack without holding shift and ctrl causes the game to crash.

**Comment by BeansGalaxy** [comment]
I deleted a line of code that checks if what I'm taking actually exists. Since no item exists in that slot the game was crashing. That check is present when taking items from a worn backpack so this bug slipped by. This'll be fixed in 20.1-0.8-v2 & 20.2-0.13-v2. 
For now just take stuff that's real, you'd be the worst thief in the world.
