### ISSUE TITLE
Add Configuration to Remove Elytra From Backslot Entirely

### ISSUE THREAD

**Issue by Alvin21Bon** [BeansGalaxy/Beans-Backpacks-2#49]
**Issue**
Currently, there is no configuration possible to remove the Elytra from the backslot while still being able to equip backpacks. 

**Why is this an issue?**
This mod is terrific at solving the inventory cluttering issue in a polished vanilla manner - definitely one of the best designs for a backpack mod. But, I was hoping there would be an option to just disable the elytra in the backslot feature because I personally feel like it doesn't fit in vanilla to wear both an elytra and a chestplate, and I would like to turn this off in the modpack I am making.

**More Info**
In my modpack, I plan on only activating the leather backpack. This will be beneficial in the lategame when elytras and skulker boxes are acquired, since the player will be able to store 4 shulker boxes in the backpack while using the elytra. I think this will be a great vanilla expansion to the storage problem, while not also being too overpowered. Thank you for making this mod by the way! It's very polished for a first time mod. I like how the backpacks float in water.

**Elytra overlaps with the backpack**
Backpack with wings? I am not sure the solution, but I feel that its so useful the configuration option should at least exist.

**Comment by BeansGalaxy** [comment]
### Removing Elytra
The elytra can be removed from the back slot by adding it to the `disables_back_slot` item list. This means Elytras can be worn in the chestplate slot but once equipped disables the ability to wear a backpack. [Create Your Own](https://github.com/BeansGalaxy/Beans-Backpacks-2/blob/20.1/assets/examples/Create%20Your%20Own.md) has a guide to follow along to, you just need to make a datapack.

### Shulker Boxes and Backpacks
I'm one of those players that thinks the shulker and elyrtra are very, very strong items (not overpowered because thats what makes them end game items). Backpacks are made to fix what shulker boxes miss in terms of inventory management. I imaging you might show up to a build with a shulker box full of stacks of wood, and finish the build with a backpack full of fences, trapdoors, stairs, etc... Shulkers are used for one thing and Backpacks are for another.

### Elytras and Backpacks
The Elytra is the most powerful item in minecraft, also, yeah it if you wear them both they clip and looks non-vanilla/pretty ugly. So thats why I keep them disabled from one another, do you want to travel quick with less inventory or take your time traveling with more room for loot. 

> I do like the idea of a backpack with wings, maybe make them crafted with a leather backpack to still balance the amount of items you can hold and make elytra dyable? But then I'd want to make all elytra's dyable and I'd want to implement this right so I'll make a note to get to this later.

### Finally, 
I'm all for adding everything you've said as config options, but my config isn't too robust, I don't like using forge's config because you'd need to install a config mod on fabric and I want my mod to include everything in one package. I'll have to look into how to cleanly implement data that can easily override previous entries. <br>
Also I need to write a more organized wiki. I keep adding info to the mod description and it's getting long and messy, so people don't read the whole thing and fill up the issues with info that's out there. Since its a reoccurring problem then it means its a problem with the information not the players.
> Just checked and I don't even have the removing Elytra info in the desc even though I've answered that 4-5 times. Clearly a problem with the info.

**Comment by Alvin21Bon** [comment]
I appreciate how much it seems you emphasize a balanced design that fits into vanilla gameplay, especially when many other backpack mods seem to just give you infinite storage with no tradeoffs. You're definitely right about shulker boxes being very powerful; I even thought about disabling shulker boxes entirely and solely relying on your mod to fix inventory issues. But, I found that issues with just carrying too many stacks of items were still too prevalent and they also give a great incentive for conquering The End other than the elytra. 

The problem with shulker boxes though is that I personally find that they make too many inventory solutions irrelevant, since you can always just carry one more shulker box and then even store more in an ender chest. I understand as you said it's an endgame resource and only becomes a problem once you start farming shulkers/exploring more end cities, but I still find it very powerful even when accounting for that.

This is the reason why I see the backpacks as more of an early-game inventory solution like the bundle, which then get superseded by shulker boxes.**Don't get me wrong: I don't see this as a problem with your mod and its design**, but moreso an issue I have with already existing vanilla mechanics. That is why I find that having shulker boxes in backpacks (in my modpack, only leather backpacks) or an elytra equipped at the same time aren't issues, since shulker boxes bypass these constraints already. 

I don't say all this to discredit your mod at all, again it is incredible and I am very glad I found it or else I would've needed to use something like traveler's backpacks, which is just way too crazy. I just think trying to find a design that balances around vanilla mechanics very interesting since we were on that topic.   

**As for configuration**, I do not have anything concrete to think about since I am not a mod developer. But, I feel like a ton of mods utilize the cloth config API which is a cross-loader solution. Although it is not just one package as you said, the configs could still be manually edited in the configs folder without it so technically it would work by itself. Overall on fabric, I imagine it's hard to keep everything one package since its ecosystem is very modular compared to forge.

**Comment by BeansGalaxy** [comment]
Don't worry about calling features in my mod bad or not fully thought out, I typically use this mod in creative mode so I am all for hearing what I could've missed. 

I'm planning out ideas to implement the winged backpack, I'm kinda realizing how strong the shulker box & elytra are. The choice between a winged backpack and a netherite backpack is a better balance I think. I'm unsure how to balance with shulker boxes except to increase the size of all the backpacks or maybe backpacks are just early-mid game and shulkers are endgame. I'll keep thinking about it.

I'll look into cloth config since you say its cross-loader but I thought its mainly for client mods. I personally don't like cluttering the mods folder but if it solves the issues I have then idk why I wouldn't.

**Comment by BeansGalaxy** [comment]
Added everything from this thread to my to-do list and also created a wiki. :)

**Comment by Alvin21Bon** [comment]
Sorry for the late reply back, I haven't been able to get a lot of time on my laptop. 

> Added everything from this thread to my to-do list and also created a wiki. :)
> Thanks for your feedback

Thank you for considering my feedback, I'm glad to have helped because I personally feel like this is the best backpack mod on modrinth right now and the effort clearly shows. The wiki is looking good by the way :)

**For balancing around the shulker box**, it is definitely very hard since shulker boxes are such an everything solution for inventory problems. Although the backpacks would still be handy for its purpose of decluttering even with shulker boxes, I feel that shulkers would still diminish these needs a lot since inventory space is essentially unlimited and most resources in the endgame will be mostly stack-full anyway. Of course, I haven't done a full playthrough with the mod albeit just a lot of testing, so this is all mostly theoretical. One thing for sure is that backpacks are a lot quicker to deploy and interact with than the shulker box, so maybe it is a really good for quality of life purposes by then. These are just some more thoughts while mulling it over some more, it is definitely hard to approach so I appreciate the amount of game design effort you are putting into this rather than just making shulker box part 2 like other mods.

> I'll look into cloth config since you say its cross-loader but I thought its mainly for client mods. I personally don't like cluttering the mods folder but if it solves the issues I have then idk why I wouldn't.

I can't be 100% about this since I have never worked with it before, but I believe it can be for both. For example, the library [Valyrien Skies](https://modrinth.com/mod/valkyrien-skies) uses it for its configurations, and it has different tabs in game (via [mod menu](https://modrinth.com/mod/modmenu)) for customizing both its client-side and server-side configurations.
