### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by ApionXD** [BeansGalaxy/Beans-Backpacks-2#6]
I really like your mod, and wanted to include it in a modpack because the concepts were really cool. I really like the stack like functionality of the backpack, and I love the aesthetics of the menu+models. However:

- It is very unclear how to interact with the backpack without consulting the docs. I don't want to make players only use this backpack mod if they wont be able to figure out how to use the backpack. Unsure how to fix this, maybe a guide book? Or some toast messages? Advancements? Not sure. 

- Non configurable keybinds. Tieing the sprint button means to all the interactions makes it extremely possible people will accidentally place it down. Would be really unfortunate if someone accidentally left their backpack behind.

- No backpacks in creative. Not the fact that you can't USE them in creative, but the fact that you can't grab them from a menu. Can't even use /give unless you know what to specify in the NBT. Made it pretty hard to just look around at it.

As I said, I really like the flow of this mod, but with these missing features I find it difficult to include it as the only backpack mod in my modpack. Anything you could do to address them would be really cool.

**Comment by BeansGalaxy** [comment]
1. I couldn't find any way that wasn't annoying or jumps out at you, but I haven't thought about toast messages. Never thought of this being an issue in a mod pack so I'll implement some tutorials in-game.
2. I really like how it feels and I disabled the ability to place it while you are sprinting and click a block with a use but I've had so much time to get used to the controls I know I'm bias. Just thought of the idea to have a bind but if it's unbound then it pairs with the sprint key.
3. I don't understand how to add Items to the creative tab with nbt but I know there are paintings with nbt so I'll check out how they did it and see what I can do. What I've been doing is just crafting them and saving them to the custom tab but, yeah... it's annoying.

I love this feedback and I'll add these features in the 1.20.2 v2 soon.

**Comment by BeansGalaxy** [comment]
For the sake of closing this issue, here's what I added since this post:

- Info in the tool tip of equipped backpacks with zero items in them. 
  -  I tried for it not to be intrusive to familiar players but out in the open once you begin with the mod.
- An advancement screen to guide players through all the main features. 
- Key binds are configurable. 
  - I might change it so if you switch the key bind you wouldn't have to also right click but for now it's just in case your issue or compatibility is a problem.
- Hover over the backpack key bind it lets you know it defaults to your sprint key. 
  - Figured it might be confusing to some players if they see it unbound, but annoying if it was bound to CTRL and you'd get a conflict.
- Backpacks to the creative screen, and in JEI (forge) and REI (fabric). 
    -  I couldn't get the recipes to display in JEI/REI because the recipe code is **_super_** advanced compared to everything I know and I can't find any documentation that is useful to my specific use case. If I can add the recipes through the recipe book then I'd drop JEI/REI support and stick with that. It's just tricky since I also have support for adding your own backpacks through a data pack.
- Also by coincidence, nbt is now simplified to just holding the key for the type of backpack if for some reason you'd want to use /give. {display:{key:"iron"}}
