### ISSUE TITLE
[Bug] Broken EMI recipes

### ISSUE THREAD

**Issue by nimbXnumb** [BeansGalaxy/Beans-Backpacks-2#61]
Mod version:
20.1 - 0.12-v2
Minecraft version:
1.20.1 Fabric

Bug description:
Broken recipes for all of the backpacks when using EMI

**Comment by BeansGalaxy** [comment]
I'll look into adding support for it, for now JEI is supported in Forge and REI is supported in Fabric but this mod looks super nice

**Comment by BeansGalaxy** [comment]
You can add custom backpacks through data packs so I just have a dyable item `beansbackpacks:backpack`, a trimmable item `beansbackpacks:metal` and a trimmable fire proof one `beansbackpacks:upgraded`. So the nbt tells my mod to read the list of added backpacks for its other properties.

Since looking into support I've gone down a rabbit hole of re-thinking this whole system since JEI & REI work but aren't perfect. Can you attach a link to the code you use to fix that, I'm unfamiliar with KubeJS so somewhere to start would help

> Also after all this in the latest snapshot mojang decides to remove nbt and the new system has all the answers I'm looking for.

**Comment by SaltSouls** [comment]
Here is an example of what I mean when using KubeJS:
```js
ServerEvents.recipes(event => {

    let leather_backpack = Item.of('beansbackpacks:backpack', '{display: {key:"leather"}}').strongNBT()
    let iron_backpack = Item.of('beansbackpacks:metal_backpack', '{display: {key:"iron"}}').strongNBT()

    event.shaped(leather_backpack, [
        'SLS',
        'LGL',
        'LLL'
    ], {
        L: 'kubejs:leather_sheet',
        S: 'kubejs:leather_strip',
        G: MC('gold_nugget')
    }).id('beansbackpacks:leather_backpack')

    event.shaped(iron_backpack, [
        'PDP',
        'IBI',
        'III'
    ], {
        I: MC('iron_ingot'),
        B: leather_backpack,
        D: MC('diamond'),
        P: MC('phantom_membrane')
    }).id('beansbackpacks:iron_backpack')

})
```
The part I refer to is the `strongNBT()` function being called. Somehow that is telling the recipe/EMI that it requires this item with this exact NBT data. I'm not sure how specifically that is working as I haven't looked through the KJS code, but I know that without `strongNBT()` the recipe will display a null texture square in place of the backpack and won't specify the NBT requirements when being used as an ingredient.

**Comment by BeansGalaxy** [comment]
Solved a LONG time ago and I guess I never closed it :) have a good day
