### ISSUE TITLE
Vanilla recipe book/advancement issues

### ISSUE THREAD

**Issue by Murdyll** [BeansGalaxy/Beans-Backpacks-2#64]
There doesn't appear to be a way to naturally proc the acquisition of the Leather Backpack recipe for Minecraft's native recipe book feature. However, crafting a Leather Backpack does grant the Iron Backpack recipe.

Once acquired (through commands), all the backpack recipes act as if they are able to be crafted without a crafting table, but these "reduced cost" recipes don't actually function.

In addition, some of the advancements seem to be failing to trigger, such as "fill a leather backpack", or "move items with a hopper" (in fact, the hopper functionality doesn't seem to be working at all, or I'm just misunderstanding it).

**Comment by BeansGalaxy** [comment]
Also, you mean hoppers aren't working at all?

**Comment by BeansGalaxy** [comment]
"Fill a Leather Backpack" was checking wrong and "Dye a Leather Backpack" has been renamed to "Equip a Dyed Backpack". I cleaned up some hopper code in the latest commit but I couldn't recreate the hoppers not working.
Closing this issue and adding recipe book recipe's to my to-do since they're stable and I'll have to come back to them.

**Comment by Murdyll** [comment]
> Also, you mean hoppers aren't working at all?

That's what I'm not sure about. This could be a "skill issue", but I can't seem to get hoppers to interact with backpacks in any way. What exactly is it that they are supposed to do?

By the way, thanks so much for this mod; it's exactly what I was after. Basing them on Bundles rather than Shulker Boxes is so much more interesting :)

**Comment by BeansGalaxy** [comment]
Thank you!! I think backpack mods are kinda stupid since they just feel like a cheap version of shulkers. Kinda like using a data pack to add a recipe for diamonds to a dirt block. I'm glad you're liking my spin on the idea. 

Hoppers just pull items out like if a minecart chest was on top of them. It could be a visual desync, check if the hopper has items in it because I'm aware of a bug that causes ghost items if many stacks are pulled out.

And I don't know if you're using the latest version (wait until <ins>20.1</ins>-0.16-v2, critical bugs in 0.15) but Recipe's are working in the Recipe Book now. I didn't realize you have to gift the recipe's to players using advancements. I'm glad I checked my closed issues, hopefully this cleared things up.
