### ISSUE TITLE
[Breaking] All backpack contents disappear when equipping the backpack in latest update

### ISSUE THREAD

**Issue by Alvin21Bon** [BeansGalaxy/Beans-Backpacks-2#72]
# Issue
When equipping a placed backpack while there are contents inside of the backpack, all items inside disappear.

# Steps to Reproduce
- Fill backpack with items
- If backpack is not already placed on the ground, place it on the ground via keybind or by dying 
- Equip the backpack with the keybind

**Note**: this bug was introduced in the latest release, it seems it does not exist in the previous version

> Minecraft 1.20.1
> Fabric loader 0.15.7
> Fabric API 0.92.0
> Beans Backpacks 20.1 - 0.15-v2

**Comment by BeansGalaxy** [comment]
I hate these are the circumstances we always get to meet but good to see you again! :P

I accidentally removed-ish the code that adds the items into your Back-Slot inventory while changing Ender Packs since Ender Data doesn't care what's in the backpack cause its items are stored elsewhere. So when equipping the ***All*** backpacks the contents would be ignored when it should just ignore Ender Packs. 

Will be fixed in <ins>20.1</ins>-0.16-v2

**Comment by Alvin21Bon** [comment]
Nice thank you for the quick updates on these features/fixes. 

> I hate these are the circumstances we always get to meet but good to see you again! :P

avid beans backpacks enjoyer and bugtester lol. Seriously though, good work on the mod so far
