### ISSUE TITLE
[Bug] Minor issue with inventory texture bug

### ISSUE THREAD

**Issue by VitaminJake** [BeansGalaxy/Beans-Backpacks-2#76]
Issue occurs with multiple versions, including latest (0.16)

When using /give commands to give a backpack to a player there is a bug causing the inventory item picture not to display. The backpacks can still be pulled from creative mode inventory just fine, so this is what we use. However, if you /give a player one and they try to equip it, it hard crashes the game. This will lock the server out permanently until an uninstall/reinstall of the mod.

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "com.beansgalaxy.backpacks.core.Kind.isTrimmable()" because "kind" is null

https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/162518177/f0b1b062-bbf3-4a4d-a071-692a62944ddd

**Comment by BeansGalaxy** [comment]
It's because every backpack holds a `key` that references a list with it's recipe, size, textures... Since you summoned it in, it gave you a backpack with no key and also no texture. I don't know how to remove the item from /give but I'll look into adding a special command. 

Creative mod is a mess rn, but I think everything is finished in terms of survival. I'm just starting to go over everything else so it's super polished for the full release.

**Comment by VitaminJake** [comment]
Ah understandable, we only encountered it because we were testing to see if we'd fixed other bugs/mod conflicts. Makes sense why it happens. Thanks for the fast response, holy wow

**Comment by BeansGalaxy** [comment]
Ahaha I want this mod out of beta already so I'm just staring at the Issues page waiting for anything to pop up.
