### ISSUE TITLE
Windows detected a Trojan.

### ISSUE THREAD

**Issue by LunarGhost** [BeansGalaxy/Beans-Backpacks-2#83]
I have used the old version with no problem for about a week or so, and now both the new and old versions of the mod suddenly got flagged by Windows Security.

![Untitled](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/554851/0cbb8dae-a334-4940-b6ab-6c56bdafce98)
![Untitled2](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/554851/1b32033c-f36c-47a8-a463-ab6d014e1dbd)

**Comment by BeansGalaxy** [comment]
Uhh... I know saying this isn't a virus is exactly what someone who gave you a virus would say but... it's just a silly backpack mod. Maybe it's because I just implemented a way to save data to your world file while I added Ender Backpacks. Is this the first version with ender backpacks you've played?  Other than that I'm unsure what could set that off lol.

**Comment by LunarGhost** [comment]
Okey, i have never played with a backpack mod before. But if you say its is fine i will just have to add it to the firewall or something. ^^

**Comment by BeansGalaxy** [comment]
File saving is a new concept to me so maybe my code's sloppy and setting off alarms, I promise I'm only mining for diamonds not data

**Comment by BeansGalaxy** [comment]
Re-opening this issue incase I get duplicates. Today my own PC flagged my mod as a virus so I'm looking for a fix. It must be the "Fracturiser malware" thing that causes windows to be overly cautious.

**Comment by BeansGalaxy** [comment]
No longer happens in the latest versions, I think the version name was setting off red flags. Closing this since it seemed to fix itself (hopefully)
