### ISSUE TITLE
Incompatibilities with Forgotten Graves

### ISSUE THREAD

**Issue by otowm** [BeansGalaxy/Beans-Backpacks-2#96]
im using Beans Backpack 0.19v2 on Fabric 1.20.1 with Forgotten Graves 3.2.5
everytime that i die all the items inside the backpack dissapears

**Comment by BeansGalaxy** [comment]
Grave mods and my mod don't get along. I know Universal Graves has support with my mod but as for Forgotten Graves, I can't see what the issue is just by looking at it. I assume it clears the player's inventory after it collects the items for it's grave but doesn't collect the backpack. 

In my mod I try to drop the backpack as soon as possible but some grave mods try to get ahead of my code and it causes your items to disappear. I'll double check my code and see if I can package up a player's backpack sooner on death but other than that I can't fix it. I'll leave this issue open until I get a wiki page up about compatibilities.

**Comment by BeansGalaxy** [comment]
I managed collect the backpack and drop it before Forgotten Graves could delete it, keep an eye out for version 20.1-0.24-v2
