### ISSUE TITLE
When inventory full items get picked up anyway and disappear

### ISSUE THREAD

**Issue by Delfonso** [BeansGalaxy/Beans-Backpacks-2#98]
When your inventory is full and you **unequip you backpa** items get picked up anyway and disappear.

How to reproduce:
1. fill inventory
2. equip a backpack
3. unequip backpack
4. pick item up

**Comment by BeansGalaxy** [comment]
Placing the backpack with the hotkey doesn't remove the item it just sets it's count to 0. The code responsible for collecting the traits of what you have equipped never checks if the count is zero. All it saw was a backpack in the back slot and inserted the item anyway. You can still get these items if you equip a backpack manually in your inventory. 

This'll be fixed in 20.1-0.20-v2
